### Create an entity
POST {{url}}/{{prefix}}/entities
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "name": "tockkorp",
  "description": "My corp",
  "authorUuid": "cde9e935-ab0e-44c9-8f99-91943d837e85"
}

### Get entities of specific user
GET {{url}}/{{prefix}}/entities/7eb2dff3-77d3-4534-bde7-f2617aa70348/entities
Authorization: Bearer {{bearerToken}}
Accept: application/json
