### Create new client with address
POST {{url}}/{{prefix}}/clients
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "client": {
    "firstName": "Tom",
    "entityUuid": "ee30a7b5-8390-447d-81f9-b0d17a74b353"
  },
  "address": {
    "street": "Esaplande",
    "number": 6,
    "postalCode": 7000,
    "locality": "Mons",
    "country": "Belgique"
  }
}

### Get all expenditures for specific entity
GET {{url}}/{{prefix}}/clients/ee30a7b5-8390-447d-81f9-b0d17a74b353
Accept: application/json
Authorization: Bearer {{bearerToken}}

###
