DELETE {{url}}/{{prefix}}/expenditures/4607f217-aee5-435b-bebe-3304cb47a26e
Authorization: Bearer {{bearerToken}}
Accept: application/json

### Create new expenditure
POST {{url}}/{{prefix}}/expenditures/
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Vélo",
  "priceInCent": 22000,
  "entityUuid": "43a75d57-c6de-432d-8e58-ecc508e1e705"
}

### Get all expenditures for specific entity
GET {{url}}/{{prefix}}/expenditures/43a75d57-c6de-432d-8e58-ecc508e1e705
Accept: application/json
Authorization: Bearer {{bearerToken}}

###
