### Create Account
POST {{Url}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "testce@gmail.com",
  "password": "1234"
}

### Login
POST {{Url}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "1234"
}

###
