export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ENTITY_REPOSITORY = 'ENTITY_REPOSITORY';
export const SERVICE_REPOSITORY = 'SERVICE_REPOSITORY';
export const EXPENDITURE_REPOSITORY = 'EXPENDITURE_REPOSITORY';
export const CLIENT_REPOSITORY = 'CLIENT_REPOSITORY';
export const ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY';
export const CAR_REPOSITORY = 'CAR_REPOSITORY';
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';
export const ORDER_SERVICE_REPOSITORY = 'ORDER_SERVICE_REPOSITORY';

export const DATE_REFERENCE = new Date(1998,6,10);